import = [
    "~/.config/alacritty/tokyonight.toml"
]

[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font"
style = "Thin Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Light"

[font.offset]
x = 0
y = 0

[scrolling]
history = 20000
multiplier = 3

[window]
decorations = "Buttonless"
dynamic_title = true
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 16
y = 16

