import = [
    # "~/.config/alacritty/tokyonight.toml"
    "~/.config/alacritty/catppuccin-frappe.toml"
]

[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "HackGen35 Console NF"
style = "Bold"

[font.bold_italic]
family = "HackGen35 Console NF"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "HackGen35 Console NF"
style = "italic"

[font.normal]
family = "HackGen35 Console NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 20000
multiplier = 3

[window]
decorations = "Buttonless"
dynamic_title = true
dynamic_padding = true
opacity = 1

[window.padding]
x = 16
y = 16

